made hw 07
ShmelevYury/made_2019_cpp pull request #5
Opened 2019-11-26 20:57 UTC by ShmelevYury

2019-11-26 21:34 UTC, smirnov-vs requested changes

2019-11-26 21:34 UTC, smirnov-vs commented on 07/format.h
> +std::string Format(const std::string& text) {
реализация функции в .h ведет к ошибкам линковки, 1 лекция

2019-11-26 21:34 UTC, smirnov-vs commented on 07/format.h
> +std::string Format(const std::string& text, ArgsT... args) {
все аргументы скопировались в формат

2019-11-26 21:34 UTC, smirnov-vs commented on 07/format.h
> +}  // Unnamed namespace
надо понимать, что такой подход нагенерит кучу кода, который не влезет в кэш
я считаю, что проще инициализировать вектор в рантайме, пусть будет аллокация, зато скорее всего очень быстрая
ну и даже аллокацию можно убрать, если заморочиться и создать пул объектов для такого временного хранения

2019-11-27 17:04 UTC, ShmelevYury commented on 07/format.h
> +std::string Format(const std::string& text) {
Да, точно. Но почему тогда такого не случается с шаблонными функциями?

2019-11-27 17:06 UTC, smirnov-vs commented on 07/format.h
> +std::string Format(const std::string& text) {
Они по дефолту inline

2019-11-27 19:29 UTC, smirnov-vs commented
Вижу ты покопался и понял, что список инициализации все скопирует, могу дать подсказку
```
std::vector<std::string> vec;
vec.reserve(sizeof...(args));
(vec.emplace_back(to_string(std::forward<Args>(args))), ...);
```

2019-12-03 22:17 UTC, closed without merging